version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tinkerflow-postgres
    restart: always
    environment:
      POSTGRES_USER: tinkerflow_admin
      POSTGRES_PASSWORD: Q@wertyuiop
      POSTGRES_DB: tinkerflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: